---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: sock-shop
  labels:
    app: front-end

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: catalogue-sa
  namespace: sock-shop
  labels:
    app: catalogue

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-sa
  namespace: sock-shop
  labels:
    app: user

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: carts-sa
  namespace: sock-shop
  labels:
    app: carts

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: orders-sa
  namespace: sock-shop
  labels:
    app: orders

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-sa
  namespace: sock-shop
  labels:
    app: payment

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shipping-sa
  namespace: sock-shop
  labels:
    app: shipping

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: queue-master-sa
  namespace: sock-shop
  labels:
    app: queue-master