apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: queue-master
  app.kubernetes.io/name: queue-master
  app.kubernetes.io/component: microservice
  tier: backend

namespace: sock-shop

resources:
  - 17-queue-master-dep.yaml
  - 18-queue-master-svc.yaml
