apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sock-shop

commonLabels:
  app: session-db
  app.kubernetes.io/name: session-db
  app.kubernetes.io/component: database
  tier: database

resources:
  - 21-session-db-dep.yaml
  - 22-session-db-svc.yaml