apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: orders
  app.kubernetes.io/name: orders
  app.kubernetes.io/component: microservice
  tier: backend

namespace: sock-shop

resources:
  - 11-orders-dep.yaml
  - 12-orders-svc.yaml
