apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: sock-shop
  namespace: sock-shop

resources:
  - ../dev
  - ./storageclass.yaml
  - ./external-secrets/
  - ./ingress/

patchesStrategicMerge:
  - ./patches/statefulsets-patches.yaml
  - ./patches/services-patches.yaml
