apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: carts-db
  labels:
    name: carts-db
  namespace: sock-shop
spec:
  serviceName: carts-db
  replicas: 1
  selector:
    matchLabels:
      name: carts-db
  template:
    metadata:
      labels:
        name: carts-db
      # This tells Linkerd to let MongoDB traffic pass through without intercepting it
      annotations:
        config.linkerd.io/skip-outbound-ports: "27017"
    spec:
      containers:
        - name: carts-db
          image: mongo:4.0
          ports:
            - name: mongo
              containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: carts-db-data
            - mountPath: /tmp
              name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
      nodeSelector:
        kubernetes.io/os: linux
  volumeClaimTemplates:
    - metadata:
        name: carts-db-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: ebs-sc
        resources:
          requests:
            storage: 1Gi
