apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - carts-db-statefulset.yaml
  - carts-db-svc.yaml
  - carts-db-np.yaml
  - db-serviceaccount.yaml
  - db-storageclass.yaml