---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue-db
  labels:
    name: catalogue-db
  namespace: sock-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: catalogue-db
  template:
    metadata:
      labels:
        name: catalogue-db
    spec:
      containers:
        - name: catalogue-db
          image: quay.io/powercloud/sock-shop-catalogue-db:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: mysql
              containerPort: 3306
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: catalogue-data
          env:
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: MYSQL_ROOT_PASSWORD  
                name: mongodb-creds
          - name: MARIADB_DATABASE
            value: "socksdb"
      volumes:
        - name: catalogue-data
          emptyDir:
            medium: Memory
      #nodeSelector:
      #  kubernetes.io/arch: amd64
      #  node-role.kubernetes.io/worker: ""
