apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: user-db
  labels:
    name: user-db
  namespace: sock-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: user-db
  template:
    metadata:
      labels:
        name: user-db
    spec:
      containers:
        - name: user-db
          image: quay.io/powercloud/sock-shop-user-db:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: mongo
              containerPort: 27017

          securityContext:
            readOnlyRootFilesystem: false
          volumeMounts:
            - mountPath: /tmp
              name: user-db-temp-pvc
            - mountPath: /data/db-users
              name: users-db-vol
      securityContext:
        fsGroup: 999  # mongodb group
      nodeSelector:
        node-role.kubernetes.io/worker: ""
        kubernetes.io/arch: amd64

  volumeClaimTemplates:
    - metadata:
        name: user-db-temp-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
        storageClassName: standard
    - metadata:
        name: users-db-vol
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
        storageClassName: standard

