apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: sock-shop
  labels:
    name: payment
    monitor: "true"
spec:
  selector:
    name: payment
  ports:
    - name: http
      port: 80
      targetPort: 80