apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: catalogue-db-spc
  namespace: sock-shop
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "securesight-dev-catalogue-db-secret"
        objectType: "secretsmanager"
        objectAlias: password
    usePodIdentity: "true"
 