apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: catalogue-db
  namespace: sock-shop
  labels:
    name: catalogue-db
spec:
  serviceName: "catalogue-db"  
  replicas: 2
  selector:
    matchLabels:
      name: catalogue-db
  template:
    metadata:
      labels:
        name: catalogue-db
    spec:
      serviceAccountName: db-sa
      containers:
        - name: catalogue-db
          image: quay.io/powercloud/sock-shop-catalogue-db:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: catalogue-db-secret
                  key: password
            - name: MARIADB_USER
              value: root
            - name: MARIADB_DATABASE
              value: socksdb
          ports:
            - name: mysql
              containerPort: 3306
          volumeMounts:
            - name: catalogue-data
              mountPath: /var/lib/mysql
            - name: secrets-store         
              mountPath: /mnt/secrets
              readOnly: true
          securityContext:
            privileged: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
         
      volumes:                           
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: catalogue-db-spc

  volumeClaimTemplates:      
    - metadata:
        name: catalogue-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: ebs-sc
        resources:
          requests:
            storage: 1Gi   