apiVersion: v1
kind: Secret
metadata:
  name: user-db-secret
  namespace: sock-shop
  labels:
    app: user-db
    app.kubernetes.io/name: user-db
    app.kubernetes.io/component: database
type: Opaque
stringData:
  MONGODB_USER: "users"
  MONGODB_PASSWORD: "changeme"
  MONGODB_DATABASE: "users"