apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: shipping-access
  namespace: sock-shop

spec:
  podSelector:
    matchLabels:
      app: shipping

  policyTypes:
    - Ingress

  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: orders
      ports:
        - protocol: TCP
          port: 8080