apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: shipping
  app.kubernetes.io/name: shipping
  app.kubernetes.io/component: microservice
  tier: backend

namespace: sock-shop

resources:
  - 23-shipping-dep.yaml
  - 24-shipping-svc.yaml
