apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sock-shop

resources:
  - namespace.yaml
  - carts/
  - catalogue/
  - payment/
  - orders/
  - user/
  - shipping/
  - frontend/
  - queue-master/

  - rabbitmq/
  - session-db/
  - catalogue-db/
  - carts-db/
  - user-db/
  - orders-db/



