apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: payment
  app.kubernetes.io/name: payment
  app.kubernetes.io/component: microservice
  tier: backend

namespace: sock-shop

resources:
  - 15-payment-dep.yaml
  - 16-payment-svc.yaml
