apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: session-db
  namespace: sock-shop
  labels:
    app: session-db
spec:
  serviceName: "session-db"
  replicas: 2

  selector:
    matchLabels:
      app: session-db

  template:
    metadata:
      labels:
        app: session-db
      annotations:
        prometheus.io/scrape: "false"

    spec:
      securityContext:
        runAsUser: 999   
        fsGroup: 999

      containers:
        - name: session-db
          image: redis:7-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - name: redis
              containerPort: 6379

          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true

          volumeMounts:
            - name: session-db-vol
              mountPath: /data

      volumes:
        - name: session-db-vol
          emptyDir:
            medium: Memory