apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: user
  app.kubernetes.io/name: user
  app.kubernetes.io/component: microservice
  tier: backend

namespace: sock-shop

resources:
  - 25-user-dep.yaml
  - 26-user-svc.yaml
