apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: detect-shell
spec:
  kprobes:
  - call: "sys_execve"
    syscall: true
    args:
    - index: 0
      type: "string"
    selectors:
    - matchArgs:
      - index: 0
        operator: "Postfix"
        values:
        - "/bin/sh"
        - "/bin/bash"
        - "/bin/dash"