apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: orders-db
  namespace: sock-shop
  labels:
    name: orders-db
spec:
  serviceName: "orders-db"  
  replicas: 2
  selector:
    matchLabels:
      name: orders-db
  template:
    metadata:
      labels:
        name: orders-db
    spec:
      containers:
        - name: orders-db
          image: quay.io/mongodb/mongodb:org-4.4-standalone-ubuntu2204
          imagePullPolicy: IfNotPresent
          ports:
            - name: mongo
              containerPort: 27017
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: orders-db-vol
              mountPath: /data/db
            - name: orders-db-temp-vol
              mountPath: /tmp
      volumes:
          - name: orders-db-temp-vol      
            emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: orders-db-vol
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: ebs-sc
        resources:
          requests:
            storage: 1Gi   