apiVersion: v1
kind: Service
metadata:
  name: queue-master
  namespace: sock-shop
  labels:
    name: queue-master
    monitor: "true"
spec:
  selector:
    name: queue-master
  ports:
    - name: http
      port: 80
      targetPort: 80