apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: carts-db-secret
  namespace: sock-shop
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: carts-db-secret
    template:
      type: Opaque
  data:
    - secretKey: MONGO_INITDB_ROOT_USERNAME
      remoteRef:
        key: prod/carts-db
        property: MONGO_INITDB_ROOT_USERNAME
    - secretKey: MONGO_INITDB_ROOT_PASSWORD
      remoteRef:
        key: prod/carts-db
        property: MONGO_INITDB_ROOT_PASSWORD
    - secretKey: SPRING_DATA_MONGODB_URI
      remoteRef:
        key: prod/carts-db
        property: SPRING_DATA_MONGODB_URI