apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: catalogue-db-secret
  namespace: sock-shop
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: catalogue-db-secret
    template:
      type: Opaque
  data:
    - secretKey: MARIADB_ROOT_PASSWORD
      remoteRef:
        key: prod/catalogue-db
        property: MARIADB_ROOT_PASSWORD
    - secretKey: MARIADB_USER
      remoteRef:
        key: prod/catalogue-db
        property: MARIADB_USER
    - secretKey: MARIADB_PASSWORD
      remoteRef:
        key: prod/catalogue-db
        property: MARIADB_PASSWORD
    - secretKey: MARIADB_DATABASE
      remoteRef:
        key: prod/catalogue-db
        property: MARIADB_DATABASE