apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-account.yaml
  - secretstore.yaml
  - carts-db-external-secret.yaml
  - catalogue-db-external-secret.yaml
  - rabbitmq-external-secret.yaml
  - session-db-external-secret.yaml
