apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: sock-shop
  annotations:
  # TODO: replace ACCOUNT_ID with your AWS account ID and external-secrets-role with the name of the IAM role you created for External Secrets
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/external-secrets-role