apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: session-db-secret
  namespace: sock-shop
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore

  target:
    name: session-db-secret
    creationPolicy: Owner

  data:
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: prod/session-db
        property: REDIS_PASSWORD