- job_name: "carts"
  metrics_path: /probe
  params:
    module: [ default ]
    target: [ "http://carts.sock-shop.svc.cluster.local/metrics" ]
  static_configs:
    - targets: [ "json-exporter.sock-shop.svc.cluster.local:7979" ]
  relabel_configs:
    - source_labels: [ __param_target ]
      target_label: instance

- job_name: "queue-master"
  metrics_path: /probe
  params:
    module: [ default ]
    target: [ "http://queue-master.sock-shop.svc.cluster.local/metrics" ]
  static_configs:
    - targets: [ "json-exporter.sock-shop.svc.cluster.local:7979" ]
  relabel_configs:
    - source_labels: [ __param_target ]
      target_label: instance
