apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - catalogue-netpol.yaml
  - carts-netpol.yaml
  - orders-netpol.yaml
  - user-netpol.yaml
  - payment-netpol.yaml
  - shipping-netpol.yaml
  - queue-master-netpol.yaml