apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - catalogue-db-netpol.yaml
  - carts-db-netpol.yaml
  - orders-db-netpol.yaml
  - user-db-netpol.yaml
  - session-db-netpol.yaml
  - rabbitmq-netpol.yaml