apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue-config
  namespace: sock-shop
  labels:
    app: catalogue
data:
  DB_HOST: "catalogue-db"
  DB_PORT: "3306"
  DB_NAME: "socksdb"
  DB_USER: "catalogue_user"