apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping-config
  namespace: sock-shop
  labels:
      app: shipping
data:
  ZIPKIN: "zipkin.jaeger.svc.cluster.local"
  JAVA_OPTS: "-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false"