apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: carts-db
  namespace: sock-shop
spec:
  serviceName: carts-db   
  replicas: 1
  selector:
    matchLabels:
      name: carts-db
  template:
    metadata:
      labels:
        name: carts-db
    spec:
      securityContext:
        fsGroup: 999
        runAsUser: 999
        runAsGroup: 999
      containers:
        - name: carts-db
          image: quay.io/mongodb/mongodb:org-4.4-standalone-ubuntu2204
          ports:
            - containerPort: 27017
              name: mongo
          
          securityContext:
            readOnlyRootFilesystem: false

          envFrom:
            - secretRef:
                name: carts-db-secret

          volumeMounts:
            - name: carts-db-temp-vol
              mountPath: /tmp 
            - name: mongo-storage   
              mountPath: /data/db

      nodeSelector:
        node-role.kubernetes.io/worker: ""
        kubernetes.io/arch: amd64

  volumeClaimTemplates: 
    - metadata:
        name: carts-db-temp-vol
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
        storageClassName: standard
    - metadata:
        name: mongo-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
        storageClassName: standard